### ISSUE TITLE
creating a bw file

### ISSUE THREAD

**Issue by PanosFirmpas** [dpryan79/pyBigWig#17]
hello,

I'm writing a script that goes from a bam input to a bw output (it's in my github page if you feel like checking it out, input would be very welcome!).

Right now, my script outputs wiggle "strings" in a subprocess pipe to wigToBigWig(the ucsc utility). This is very convenient since wigtobigwig seems to accept the input with no concerns that the chromosomes are out of order, as long as the input per chromosome is in order 

for example:

chromosome 2 start:100 step 1: 
1
2
1
chromosome 1 start:100 step 1:
1
2
1
chromosome 2 start:200 step 1:
1
2
1
chromosome 1 start:200 step 1:
1
2
1

works fine because the input for each chromosome is in proper order.

does that work with pyBigWig?

If it does i think it should provide a nice speed boost for my script !

**Comment by dpryan79** [comment]
While you can make pyBigWig accept input like that, the resulting file will largely be useless. For a bigWig file to have normal functionality, all entries for each chromosome must be together. This is true regardless of the program used.

**Comment by PanosFirmpas** [comment]
Could you please elaborate a bit on the file being useless? the output i get seems like what you'd expect it to be (on the browser, around genomic locations we're familiar with), am I getting noise and haven't noticed?

**Comment by dpryan79** [comment]
Presumably the program you're feeding interleaved regions to sorts them before actually writing them to a file. bigWig files themselves actually require that intervals from a given chromosome be next to each other and in a sorted order in order for the indexing to work. Since pyBigWig doesn't sort the regions for you it'll produce the file with regions in the order provided...which will produce a bigWig file with a broken index.

Anyway, unless `validate=False` is used, pyBigWig will also prevent creation of a file with a broken index.

**Comment by dpryan79** [comment]
As an aside, your `bamToBigWig` program sounds like our `bamCoverage` program from deepTools.

**Comment by PanosFirmpas** [comment]
It does look very similar indeed, I'm sorry i didn't know about your tool, but well this was a nice learning experience for me !

Thank you for the comments on bigwigs, it looks like i need to do some testing!!
