### ISSUE TITLE
isBigWig segfault

### ISSUE THREAD

**Issue by seisdrum** [dpryan79/pyBigWig#48]
`pyBigWig.isBigWig(1)` and `pyBigWig.isBigBed(1)` cause segfaults using Python 2, Python 3 seems unaffected. Tested on Mac and Ubuntu.

Also, maybe related, it seems that in Python 2 `pyBigWig.pyBigWig` is not exported.

**Comment by dpryan79** [comment]
I'm not surprised, you're calling object methods directly. The appropriate syntax is:

    import pyBigWig
    bw = pyBigWig.open("test.bw")
    bw.isBigWig() # or bw.isBigBed()

`pyBigWig.pyBigWig` doesn't exist, so it can't be exported.

**Comment by seisdrum** [comment]
I see, I wasn't aware that these are strictly object methods since they are available as functions on the module level.

What I want do to do is simply checking if a variable is a pyBigWig object instance. So far I've used `isinstance(var, pyBigWig.pyBigWig)`. I'm not so sure now if this was intended, but in Python 3 `pyBigWig.pyBigWig` does point to the `pyBigWig.bigWigFile` type, so this works nicely.

What would be the suggested way to test this? I guess I could do `hasattr(var, 'isBigWig')` for now. Thank you for your help!

**Comment by dpryan79** [comment]
I guess I could remove them from the module, it was easier to just leave them in since then the documentation is easier and I didn't have to figure out how else it's all supposed to work in the python C API.

Regarding testing whether an object is a bigWig file, i've never had reason to do that and thus never implemented anything. The bigWigFile is the object that's actually returned by `open()`, so perhaps checking that with `isinstance()` works. If not, I can look into implementing something.

**Comment by dpryan79** [comment]
Ah, I found how to fix the documentation so the object methods aren't listed being directly accessible. I also found where I forgot to add the `pyBigWig` object to the module. I'll try to get a new version released with all of that fixed in the next week.

**Comment by dpryan79** [comment]
I've just pushed out a new version, where the documentation for this is fixed.
